version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
env:
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: infrastructure/
      - terraform/validate:
          checkout: true
          context: terraform
          path: infrastructure/
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          path: infrastructure/
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: infrastructure/
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
