version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: infrastructure/
      - terraform/validate:
          checkout: true
          context: terraform
          path: infrastructure/
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          path: infrastructure/
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: infrastructure/
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
